import fs from 'node:fs'
import path from 'node:path'
const source=fs.readFileSync('src/tools.ts','utf8')
const entries=[...source.matchAll(/\{slug:'([^']+)',title:'([^']+)',description:'([^']+)',icon:'([^']+)',category:'([^']+)'/g)].map(([,slug,title,description,icon,category])=>({slug,title,description,icon,category}))
const base=fs.readFileSync('dist/index.html','utf8')
const origin=(process.env.VITE_PUBLIC_ORIGIN||'').replace(/\/$/,'')
const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')
for(const t of entries){const dir=path.join('dist',t.slug);fs.mkdirSync(dir,{recursive:true});let html=base.replace(/<title>[^<]*<\/title>/,`<title>${escape(t.title)} gratis | TextHuman Hub</title>`).replace(/<meta name="description" content="[^"]*"\/>/,`<meta name="description" content="${escape(t.description)} Úsalo fácil en TextHuman Hub."/>`);const canonical=origin?`<link rel="canonical" href="${escape(origin)}/${t.slug}"/>`:'';const structured=JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:`${t.title} | TextHuman Hub`,applicationCategory:'UtilitiesApplication',operatingSystem:'Web',description:t.description,offers:{'@type':'Offer',price:'0',priceCurrency:'MXN'}}).replaceAll('<','\\u003c');html=html.replace('</head>',`${canonical}<script type="application/ld+json">${structured}</script></head>`).replace('<div id="root"></div>',`<div id="root"><main style="font-family:Arial,sans-serif;max-width:750px;margin:4rem auto;padding:1rem"><a href="/">TextHuman Hub</a><p>${escape(t.icon)} ${escape(t.category)}</p><h1>${escape(t.title)}</h1><p>${escape(t.description)}</p><p>Selecciona un archivo o escribe el contenido en esta página para obtener el resultado en tu navegador.</p><a href="/herramientas">Ver todas las herramientas</a></main></div>`);fs.writeFileSync(path.join(dir,'index.html'),html)}
if(origin&&!origin.includes('YOUR_')){const paths=['/','/herramientas','/precios',...entries.map(t=>`/${t.slug}`)];fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${escape(origin+p)}</loc></url>`).join('')}</urlset>`);fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nDisallow: /cuenta\nDisallow: /admin\nDisallow: /acceso\nSitemap: ${origin}/sitemap.xml\n`)}else fs.writeFileSync('dist/robots.txt','User-agent: *\nDisallow: /\n')
console.log(`Generated ${entries.length} indexable tool pages${origin?' and sitemap':' (set VITE_PUBLIC_ORIGIN to enable sitemap)'}.`)
