import { createClient } from '@supabase/supabase-js'
type Env={ASSETS:FetchLike;APP_ORIGIN:string;SUPPORT_TO_EMAIL:string;FREE_DAILY_LIMIT:string;FREE_MAX_FILE_MB:string;PRO_WEEKLY_MXN:string;PRO_MONTHLY_MXN:string;SUPABASE_URL:string;SUPABASE_SERVICE_ROLE_KEY:string;SUPABASE_PUBLISHABLE_KEY:string;MERCADOPAGO_ACCESS_TOKEN:string;MERCADOPAGO_WEBHOOK_SECRET:string;RESEND_API_KEY:string;SUPPORT_FROM_EMAIL:string;ADMIN_EMAIL:string}
type FetchLike={fetch(request:Request):Promise<Response>}
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function client(env:Env){if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Supabase no configurado');return createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
async function userFrom(req:Request,env:Env){const token=req.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)throw Error('Inicia sesión para usar herramientas de archivos');const {data,error}=await client(env).auth.getUser(token);if(error||!data.user)throw Error('Tu sesión expiró. Vuelve a entrar.');return data.user}
function textError(err:unknown){return err instanceof Error?err.message:'Error inesperado'}
async function mpFetch(path:string,env:Env,init?:RequestInit){if(!env.MERCADOPAGO_ACCESS_TOKEN)throw Error('Mercado Pago no configurado');const res=await fetch(`https://api.mercadopago.com${path}`,{...init,headers:{Authorization:`Bearer ${env.MERCADOPAGO_ACCESS_TOKEN}`,'Content-Type':'application/json',...(init?.headers||{})}});const data:any=await res.json();if(!res.ok)throw Error(data.message||'Mercado Pago rechazó la solicitud');return data}
async function verifySignature(req:Request,env:Env,dataId:string){if(!env.MERCADOPAGO_WEBHOOK_SECRET)return false;const x=req.headers.get('x-signature')||'',requestId=req.headers.get('x-request-id')||'';const ts=x.match(/(?:^|,)ts=([^,]+)/)?.[1],v1=x.match(/(?:^|,)v1=([^,]+)/)?.[1];if(!ts||!v1||!requestId)return false;const when=Number(ts);if(!Number.isFinite(when)||Math.abs(Date.now()-(when<1e12?when*1000:when))>300000)return false;const normalized=dataId.toLowerCase();const manifest=`id:${normalized};request-id:${requestId};ts:${ts};`;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.MERCADOPAGO_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(manifest));const hex=[...new Uint8Array(signed)].map(b=>b.toString(16).padStart(2,'0')).join('');if(hex.length!==v1.length)return false;let diff=0;for(let i=0;i<hex.length;i++)diff|=hex.charCodeAt(i)^v1.charCodeAt(i);return diff===0}
async function handle(req:Request,env:Env):Promise<Response>{const url=new URL(req.url),path=url.pathname;
  if(path==='/api/health')return json({ok:true});
  if(path==='/api/support'&&req.method==='POST'){const {email,message}=await req.json() as {email?:string,message?:string};if(!email||!/^\S+@\S+\.\S+$/.test(email)||!message||message.length<10||message.length>5000)return json({error:'Revisa el correo y el mensaje'},400);if(!env.RESEND_API_KEY||!env.SUPPORT_FROM_EMAIL)throw Error('Correo de soporte no configurado');const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.SUPPORT_FROM_EMAIL,to:[env.SUPPORT_TO_EMAIL],reply_to:email,subject:'Nuevo mensaje de soporte de TextHuman Hub',text:`De: ${email}\n\n${message}`})});if(!res.ok)throw Error('No se pudo enviar el mensaje');return json({ok:true})}
  if(path==='/api/mp-webhook'&&req.method==='POST'){const body:any=await req.json();const id=String(url.searchParams.get('data.id')||body?.data?.id||'');if(!id||!await verifySignature(req,env,id))return json({error:'Firma inválida'},401);const db=client(env);if(body.type==='subscription_preapproval'){const sub=await mpFetch(`/preapproval/${encodeURIComponent(id)}`,env);if(!sub.external_reference)return json({ok:true});const status=sub.status==='authorized'?'active':sub.status==='canceled'?'cancelled':'pending';const {error}=await db.from('subscriptions').upsert({user_id:sub.external_reference,provider:'mercadopago',provider_id:sub.id,plan:sub.auto_recurring?.frequency_type==='days'&&sub.auto_recurring?.frequency===7?'weekly':'monthly',status,valid_until:sub.next_payment_date||null,updated_at:new Date().toISOString()},{onConflict:'provider_id'});if(error)throw error}
    if(body.type==='payment'){const payment=await mpFetch(`/v1/payments/${encodeURIComponent(id)}`,env);const reference=String(payment.external_reference||'');const {error}=await db.from('payments').upsert({provider_id:String(payment.id),subscription_id:payment.metadata?.preapproval_id||null,user_id:/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(reference)?reference:null,status:payment.status,amount:payment.transaction_amount,currency:payment.currency_id,paid_at:payment.date_approved||null},{onConflict:'provider_id'});if(error)throw error}return json({ok:true})}
  if(path==='/api/usage'){const user=await userFrom(req,env),db=client(env);if(req.method==='GET'){const {data,error}=await db.rpc('hub_usage_summary',{p_user_id:user.id,p_free_limit:Number(env.FREE_DAILY_LIMIT)||2});if(error)throw error;return json(data)}if(req.method==='POST'){const body=await req.json() as {tool?:string,totalBytes?:number};if(!body.tool||!Number.isFinite(body.totalBytes)||Number(body.totalBytes)<0)return json({error:'Datos inválidos'},400);const {data,error}=await db.rpc('hub_consume_usage',{p_user_id:user.id,p_tool:body.tool,p_bytes:body.totalBytes,p_free_limit:Number(env.FREE_DAILY_LIMIT)||2,p_free_max_bytes:(Number(env.FREE_MAX_FILE_MB)||5)*1048576,p_pro_max_bytes:50*1048576});if(error)return json({error:error.message},403);return json(data)}}
  if(path==='/api/checkout'&&req.method==='POST'){const user=await userFrom(req,env);if(!user.email)throw Error('Tu cuenta necesita un correo');const {plan}=await req.json() as {plan?:string};if(plan!=='weekly'&&plan!=='monthly')return json({error:'Plan inválido'},400);const amount=plan==='weekly'?Number(env.PRO_WEEKLY_MXN):Number(env.PRO_MONTHLY_MXN);const sub=await mpFetch('/preapproval',env,{method:'POST',headers:{'X-Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({reason:`TextHuman Hub Pro ${plan==='weekly'?'semanal':'mensual'}`,external_reference:user.id,payer_email:user.email,auto_recurring:{frequency:plan==='weekly'?7:1,frequency_type:plan==='weekly'?'days':'months',transaction_amount:amount,currency_id:'MXN'},back_url:`${env.APP_ORIGIN}/cuenta`,status:'pending'})});const {error}=await client(env).from('subscriptions').upsert({user_id:user.id,provider:'mercadopago',provider_id:sub.id,plan,status:'pending'},{onConflict:'provider_id'});if(error)throw error;return json({init_point:sub.init_point})}
  if(path==='/api/cancel-subscription'&&req.method==='POST'){const user=await userFrom(req,env),db=client(env);const {data,error}=await db.from('subscriptions').select('provider_id').eq('user_id',user.id).eq('status','active').order('updated_at',{ascending:false}).limit(1).single();if(error||!data)return json({error:'No hay una suscripción activa'},404);const current=await mpFetch(`/preapproval/${encodeURIComponent(data.provider_id)}`,env);await mpFetch(`/preapproval/${encodeURIComponent(data.provider_id)}`,env,{method:'PUT',body:JSON.stringify({status:'canceled'})});const updated=await db.from('subscriptions').update({status:'cancelled',valid_until:current.next_payment_date||new Date().toISOString(),updated_at:new Date().toISOString()}).eq('provider_id',data.provider_id).eq('user_id',user.id);if(updated.error)throw updated.error;return json({ok:true})}
  if(path==='/api/admin/summary'||path==='/api/admin/users'){const user=await userFrom(req,env);if(!env.ADMIN_EMAIL||user.email?.toLowerCase()!==env.ADMIN_EMAIL.toLowerCase())return json({error:'No autorizado'},403);const db=client(env);if(path.endsWith('summary')){const [profiles,subs,events,payments]=await Promise.all([db.from('profiles').select('*',{count:'exact',head:true}),db.from('subscriptions').select('*',{count:'exact',head:true}).eq('status','active'),db.from('usage_events').select('*',{count:'exact',head:true}),db.from('payments').select('amount').eq('status','approved')]);return json({users:profiles.count||0,activeSubscriptions:subs.count||0,uses:events.count||0,revenue:(payments.data||[]).reduce((n,p)=>n+Number(p.amount||0),0)})}const {data,error}=await db.from('admin_user_overview').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;return json({users:data})}
  return json({error:'Ruta desconocida'},404)
}
export default {async fetch(req:Request,env:Env){try{if(new URL(req.url).pathname.startsWith('/api/'))return await handle(req,env);return env.ASSETS.fetch(req)}catch(err){return json({error:textError(err)},500)}}}
