export type Category = 'PDF' | 'Imágenes' | 'Audio y video' | 'Texto' | 'Desarrollo'
export type Tool = { slug:string; title:string; description:string; icon:string; category:Category; kind:'file'|'text'|'generator'; premium?:boolean; accept?:string }
export const tools:Tool[] = [
  {slug:'merge-pdf',title:'Unir PDF',description:'Junta varios PDF en uno.',icon:'📚',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'split-pdf',title:'Separar PDF',description:'Descarga cada página por separado.',icon:'✂️',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'rotate-pdf',title:'Rotar PDF',description:'Gira todas las páginas 90°.',icon:'🔄',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'number-pdf',title:'Numerar PDF',description:'Añade el número a cada página.',icon:'🔢',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'images-to-pdf',title:'Imágenes a PDF',description:'Crea un PDF con tus fotos.',icon:'🖼️',category:'PDF',kind:'file',accept:'image/png,image/jpeg'},
  {slug:'pdf-to-images',title:'PDF a imágenes',description:'Descarga cada página como PNG.',icon:'🧾',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'extract-pdf-text',title:'Extraer texto de PDF',description:'Copia el texto seleccionable.',icon:'📋',category:'PDF',kind:'file',accept:'.pdf'},
  {slug:'ocr-pdf',title:'OCR de PDF',description:'Lee texto de páginas escaneadas.',icon:'👁️',category:'PDF',kind:'file',accept:'.pdf',premium:true},
  {slug:'jpg-to-png',title:'JPG a PNG',description:'Convierte fotos a PNG.',icon:'🟡',category:'Imágenes',kind:'file',accept:'image/jpeg'},
  {slug:'png-to-jpg',title:'PNG a JPG',description:'Convierte a JPG con fondo blanco.',icon:'🔵',category:'Imágenes',kind:'file',accept:'image/png'},
  {slug:'image-to-webp',title:'Imagen a WebP',description:'Reduce peso para tu web.',icon:'🪶',category:'Imágenes',kind:'file',accept:'image/*'},
  {slug:'resize-image',title:'Redimensionar imagen',description:'Elige ancho y alto.',icon:'📐',category:'Imágenes',kind:'file',accept:'image/*'},
  {slug:'compress-image',title:'Comprimir imagen',description:'Optimiza el tamaño.',icon:'🗜️',category:'Imágenes',kind:'file',accept:'image/*'},
  {slug:'remove-exif',title:'Quitar metadatos',description:'Exporta una copia sin EXIF.',icon:'🧼',category:'Imágenes',kind:'file',accept:'image/*'},
  {slug:'favicon',title:'Crear favicon',description:'Genera un icono cuadrado.',icon:'✨',category:'Imágenes',kind:'file',accept:'image/*'},
  {slug:'mp4-to-mp3',title:'MP4 a MP3',description:'Saca el audio de un video.',icon:'🎵',category:'Audio y video',kind:'file',accept:'video/mp4'},
  {slug:'wav-to-mp3',title:'WAV a MP3',description:'Convierte audio WAV a MP3.',icon:'🎧',category:'Audio y video',kind:'file',accept:'audio/wav'},
  {slug:'m4a-to-mp3',title:'M4A a MP3',description:'Convierte audio M4A a MP3.',icon:'🎙️',category:'Audio y video',kind:'file',accept:'audio/mp4,.m4a'},
  {slug:'webm-to-mp4',title:'WEBM a MP4',description:'Convierte video WEBM a MP4.',icon:'🎬',category:'Audio y video',kind:'file',accept:'video/webm'},
  {slug:'mov-to-mp4',title:'MOV a MP4',description:'Convierte video MOV a MP4.',icon:'📹',category:'Audio y video',kind:'file',accept:'.mov'},
  {slug:'video-to-gif',title:'Video a GIF',description:'Crea un GIF de los primeros segundos.',icon:'🎞️',category:'Audio y video',kind:'file',accept:'video/*'},
  {slug:'gif-to-video',title:'GIF a video',description:'Convierte GIF a MP4.',icon:'▶️',category:'Audio y video',kind:'file',accept:'image/gif'},
  {slug:'trim-audio',title:'Cortar audio',description:'Elige inicio y duración.',icon:'✂️',category:'Audio y video',kind:'file',accept:'audio/*'},
  {slug:'trim-video',title:'Cortar video',description:'Recorta un fragmento.',icon:'✂️',category:'Audio y video',kind:'file',accept:'video/*'},
  {slug:'compress-audio',title:'Comprimir audio',description:'Reduce la calidad para ahorrar espacio.',icon:'🗜️',category:'Audio y video',kind:'file',accept:'audio/*'},
  {slug:'compress-video',title:'Comprimir video',description:'Reduce el tamaño de tu video.',icon:'🗜️',category:'Audio y video',kind:'file',accept:'video/*',premium:true},
  {slug:'audio-speed',title:'Velocidad de audio',description:'Acelera o ralentiza audio.',icon:'⏩',category:'Audio y video',kind:'file',accept:'audio/*'},
  {slug:'video-speed',title:'Velocidad de video',description:'Acelera o ralentiza video.',icon:'⏩',category:'Audio y video',kind:'file',accept:'video/*',premium:true},
  {slug:'word-counter',title:'Contar palabras',description:'Mide palabras y caracteres.',icon:'📝',category:'Texto',kind:'text'},
  {slug:'clean-text',title:'Limpiar texto',description:'Quita espacios repetidos.',icon:'🧹',category:'Texto',kind:'text'},
  {slug:'change-case',title:'Mayúsculas y minúsculas',description:'Cambia las letras al instante.',icon:'🔠',category:'Texto',kind:'text'},
  {slug:'slug-generator',title:'Crear slug',description:'Prepara texto para una URL.',icon:'🔗',category:'Texto',kind:'text'},
  {slug:'json-formatter',title:'Formatear JSON',description:'Ordena y valida datos JSON.',icon:'🧩',category:'Desarrollo',kind:'text'},
  {slug:'json-to-csv',title:'JSON a CSV',description:'Pasa una lista de objetos a tabla.',icon:'📊',category:'Desarrollo',kind:'text'},
  {slug:'csv-to-json',title:'CSV a JSON',description:'Convierte filas en objetos.',icon:'🗂️',category:'Desarrollo',kind:'text'},
  {slug:'base64',title:'Base64',description:'Codifica o decodifica texto.',icon:'🔐',category:'Desarrollo',kind:'text'},
  {slug:'url-encoder',title:'Codificar URL',description:'Codifica o decodifica enlaces.',icon:'🌐',category:'Desarrollo',kind:'text'},
  {slug:'jwt-decoder',title:'Leer JWT',description:'Inspecciona datos sin verificar firma.',icon:'🪪',category:'Desarrollo',kind:'text'},
  {slug:'hash-generator',title:'Hash SHA-256',description:'Calcula la huella del texto.',icon:'🧬',category:'Desarrollo',kind:'text'},
  {slug:'timestamp',title:'Fecha Unix',description:'Convierte fecha y timestamp.',icon:'⏱️',category:'Desarrollo',kind:'text'},
  {slug:'uuid-generator',title:'Generar UUID',description:'Crea identificadores únicos.',icon:'🆔',category:'Desarrollo',kind:'generator'},
  {slug:'password-generator',title:'Generar contraseña',description:'Crea una clave fuerte.',icon:'🛡️',category:'Desarrollo',kind:'generator'},
  {slug:'qr-generator',title:'Crear QR',description:'Convierte un enlace en código QR.',icon:'▦',category:'Desarrollo',kind:'text'},
]
export const categories:Category[]=['PDF','Imágenes','Audio y video','Texto','Desarrollo']
